#во вкладке marketplace/actions можно брать уже готовые написаные Actions
#checkout - action который предоставлен командой github и позволяет получить исходный код на сервере 
#uses - для использования уже готового action нужно использовать команду uses, а не run
#npm ci - выполняет тоже что и npm install, но рекомендуется делать npm ci, но обязательно должен присутствовать package-lock
#needs: 'имя работы' - пзволяет связать работы и запустить их последовательно, а не параллельно
#paths-ignore: добавить игнорируемый путь
name: Deploy react app
on: 
  push:
    branches:
      - master
    #paths-ignore:
    # - '.github/workflows/*'
jobs:
  test:
    runs-on: windows-latestasd
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ hashFiles('**/package-lock.json') }}-primes
      - name: Install react dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ hashFiles('**/package-lock.json') }}-primes
      - name: Install react dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  build:
    runs-on: windows-latest
    needs: lint
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ hashFiles('**/package-lock.json') }}-primes
      - name: Install react dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Deploy
        run: echo Deploying...
