#${{ expression }} - вывести в консоль объект контекст github action expressions
name: Print pull request
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print context
        run: echo ${{ toJSON(github) }}