#во вкладке marketplace/actions можно брать уже готовые написаные Actions
#checkout - action который предоставлен командой github и позволяет получить исходный код на сервере 
#uses - для использования уже готового action нужно использовать команду uses, а не run
#npm ci - выполняет тоже что и npm install, но рекомендуется делать npm ci, но обязательно должен присутствовать package-lock
name: Test react app
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Instal react dependencies
        run: npm ci
      - name: Test application
        run: npm run test
